name: Publish Release

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          token: ${{ secrets.github_token }}
